"""add portfolio monthly nav cache

Revision ID: 05b51bcef828
Revises: 91dd8f7e38bd
Create Date: 2025-10-24 17:09:57.482573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b51bcef828'
down_revision = '91dd8f7e38bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_monthly_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_end', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('total_units', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('nav_per_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('capital_flow', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('needs_refresh', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_pmnav_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month_end', name='uq_portfolio_monthly_nav_user_month')
    )
    with op.batch_alter_table('portfolio_monthly_nav', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_monthly_nav_needs_refresh'), ['needs_refresh'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_monthly_nav_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_monthly_nav', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_monthly_nav_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_monthly_nav_needs_refresh'))

    op.drop_table('portfolio_monthly_nav')
    # ### end Alembic commands ###
