"""Add pf share price and shares into Trades

Revision ID: 4bef3281dcfb
Revises: f15aec6c8c5b
Create Date: 2021-06-20 18:45:37.178007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bef3281dcfb'
down_revision = 'f15aec6c8c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('pf_price', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('trades', sa.Column('pf_shares', sa.Numeric(precision=20, scale=10), nullable=True))
    op.create_index(op.f('ix_trades_pf_price'), 'trades', ['pf_price'], unique=False)
    op.create_index(op.f('ix_trades_pf_shares'), 'trades', ['pf_shares'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_pf_shares'), table_name='trades')
    op.drop_index(op.f('ix_trades_pf_price'), table_name='trades')
    op.drop_column('trades', 'pf_shares')
    op.drop_column('trades', 'pf_price')
    # ### end Alembic commands ###
