"""Add stocks table and currency col

Revision ID: 58ea48d37523
Revises: d6572503f2ec
Create Date: 2021-04-26 18:24:14.807915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58ea48d37523'
down_revision = 'd6572503f2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
                    sa.Column('ticker', sa.String(length=20), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.Column('currency', sa.String(length=10), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('ticker')
                    )
    op.create_index(op.f('ix_stocks_currency'),
                    'stocks', ['currency'], unique=False)
    op.create_index(op.f('ix_stocks_last_updated'),
                    'stocks', ['last_updated'], unique=False)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    op.alter_column('trades', 'ticker',
                    existing_type=mysql.VARCHAR(
                        charset='utf8', collation='utf8_general_ci', length=20),
                    nullable=False)
    op.create_index(op.f('ix_trades_ticker'),
                    'trades', ['ticker'], unique=False)
    op.add_column('user', sa.Column('default_currency', sa.String(
        length=10), server_default='AUD', nullable=False))
    op.create_index(op.f('ix_user_default_currency'), 'user',
                    ['default_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_default_currency'), table_name='user')
    op.drop_column('user', 'default_currency')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.alter_column('trades', 'ticker',
                    existing_type=mysql.VARCHAR(
                        charset='utf8', collation='utf8_general_ci', length=20),
                    nullable=True)
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_last_updated'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_currency'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
