"""Remove fx column

Revision ID: 5fe6c3fdbeee
Revises: 656a4c6b9454
Create Date: 2023-03-28 15:37:12.572454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fe6c3fdbeee'
down_revision = '656a4c6b9454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_fx')
        batch_op.drop_column('fx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fx', mysql.DECIMAL(precision=20, scale=10), nullable=True))
        batch_op.create_index('ix_trades_fx', ['fx'], unique=False)

    # ### end Alembic commands ###
