"""Added stock prices database

Revision ID: 656a4c6b9454
Revises: c06ff54ec59d
Create Date: 2023-03-15 21:22:01.651466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656a4c6b9454'
down_revision = 'c06ff54ec59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(length=20), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('open', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('high', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('low', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('close', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('volume', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('adjclose', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('dividends', sa.Numeric(precision=40, scale=20), nullable=True),
                    sa.Column('splits', sa.Numeric(precision=20, scale=10), nullable=True),
                    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], name='fk_prices_ticker'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_prices_adjclose'), ['adjclose'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_close'), ['close'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_dividends'), ['dividends'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_high'), ['high'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_low'), ['low'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_open'), ['open'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_splits'), ['splits'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_volume'), ['volume'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_volume'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_splits'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_open'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_low'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_high'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_dividends'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_date'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_close'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_adjclose'))

    op.drop_table('stock_prices')
    # ### end Alembic commands ###
