"""Added unique constraint on StockPrices

Revision ID: 91dd8f7e38bd
Revises: 5fe6c3fdbeee
Create Date: 2023-03-31 12:08:30.598066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dd8f7e38bd'
down_revision = '5fe6c3fdbeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_ticker_date', ['ticker', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ticker_date', type_='unique')

    # ### end Alembic commands ###
