"""Add foreign key constraint to trades.ticker

Revision ID: 99759eab18b7
Revises: 58ea48d37523
Create Date: 2021-04-26 18:26:17.978547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99759eab18b7'
down_revision = '58ea48d37523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'ticker',
                    existing_type=mysql.VARCHAR(
                        charset='utf8', collation='utf8_general_ci', length=20),
                    nullable=False)
    op.drop_index('ix_trades_ticker', table_name='trades')
    op.create_foreign_key('fk_trades_ticker', 'trades',
                          'stocks', ['ticker'], ['ticker'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trades_ticker', 'trades', type_='foreignkey')
    op.create_index('ix_trades_ticker', 'trades', ['ticker'], unique=False)
    op.alter_column('trades', 'ticker',
                    existing_type=mysql.VARCHAR(
                        charset='utf8', collation='utf8_general_ci', length=20),
                    nullable=False)
    # ### end Alembic commands ###
