"""Add fx rate at trade date

Revision ID: c06ff54ec59d
Revises: 4bef3281dcfb
Create Date: 2021-06-20 18:52:25.157431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06ff54ec59d'
down_revision = '4bef3281dcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fx', sa.Numeric(precision=20, scale=10), nullable=True))
    op.create_index(op.f('ix_trades_fx'), 'trades', ['fx'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_fx'), table_name='trades')
    op.drop_column('trades', 'fx')
    # ### end Alembic commands ###
