"""add dividend flow to monthly nav

Revision ID: cd6f9748ab5f
Revises: 05b51bcef828
Create Date: 2025-10-27 17:52:23.736808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6f9748ab5f'
down_revision = '05b51bcef828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_monthly_nav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_flow', sa.Numeric(precision=20, scale=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_monthly_nav', schema=None) as batch_op:
        batch_op.drop_column('dividend_flow')

    # ### end Alembic commands ###
