"""Add user.last_accessed column

Revision ID: f15aec6c8c5b
Revises: 99759eab18b7
Create Date: 2021-04-26 18:35:31.465228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15aec6c8c5b'
down_revision = '99759eab18b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_last_accessed'), 'user', ['last_accessed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_accessed'), table_name='user')
    op.drop_column('user', 'last_accessed')
    # ### end Alembic commands ###
